include:
  - ./Enrichment/docker-compose.yaml
  - ./MISP/docker-compose.yaml
  - ./NATS/docker-compose.yaml
  - ./Vector/docker-compose.yaml

services:
  resilmesh_ap_silentpush_redis:
    hostname: "redis"
    restart: unless-stopped
    image: redis
    container_name: redis
    ports:
      - 6378:6378
    networks:
      resilmesh_network:

networks:
  resilmesh_network:
#    external: true
    name: resilmesh_network
